id: default-oracle-application-page

info:
  name: Oracle Application Server Containers
  author: dhiyaneshDk,righettod
  severity: info
  metadata:
    max-request: 1
    shodan-query: http.title:"Oracle Application Server Containers"
  tags: tech,oracle

http:
  - method: GET
    path:
      - '{{BaseURL}}'

    matchers:
      - type: word
        words:
          - "<TITLE>Oracle Application Server"
        part: body

    extractors:
      - type: regex
        part: body
        group: 1
        regex:
          - '(?i)\s+\(([0-9.]+)\)'
# digest: 4a0a0047304502203709028b7add9432a486624c46eee996bbd06f8f692272b6cc7fe0aa4fa8fcbf02210089d3596b1bd759c78e613b064c1eca34fb40bc6cccead5c23eb7f6a2d7535c1d:922c64590222798bb761d5b6d8e72950