id: ftpconfig

info:
  name: Atom remote-ssh ftpconfig Exposure
  author: geeknik,DhiyaneshDK
  severity: high
  description: Created by remote-ssh for Atom, contains SFTP/SSH server details and credentials
  metadata:
    verified: true
    max-request: 1
    shodan-query: html:ftpconfig
  tags: atom,ftp,config,exposure,files

http:
  - method: GET
    path:
      - "{{BaseURL}}/.ftpconfig"

    matchers-condition: and
    matchers:
      - type: word
        words:
          - '"protocol":'
          - '"host":'
          - '"user":'
          - '"passphrase":'
        condition: and

      - type: status
        status:
          - 200
# digest: 4a0a0047304502203e964492aa5ae873f03597ac2a5b426d215393200bd9a91a40eb7140836f033d022100d12b8356b48603f84427b50a84d0078581d289d3d7e9f95cf8310044a880bc29:922c64590222798bb761d5b6d8e72950