id: htaccess-config

info:
  name: HTaccess config file
  author: Yash Anand @yashanand155
  severity: info
  metadata:
    max-request: 6
  tags: miscellaneous,misc,config

http:
  - method: GET
    path:
      - "{{BaseURL}}/.htaccess"
      - "{{BaseURL}}/example.htaccess"
      - "{{BaseURL}}/_.htaccess"
      - "{{BaseURL}}/sample.htaccess"
      - "{{BaseURL}}/a.htaccess"
      - "{{BaseURL}}/htaccess_for_page_not_found_redirects.htaccess"

    stop-at-first-match: true
    matchers:
      - type: word
        words:
          - RewriteRule
          - </IfModule>
          - <IfModule
        condition: and
# digest: 4a0a00473045022100ac8f1ba3da35179caa6810afa2f3dbbaf0a50162103cf75959fa156cab470617022043085378729b0e6326bb3136e751f93fa28ca0caa1a45d82be42bba9e83fcf5e:922c64590222798bb761d5b6d8e72950