id: prometheus-pushgateway-exposed-panel

info:
  name: Prometheus Pushgateway Panel - Detect
  author: codexlynx
  severity: info
  description: Prometheus Pushgateway panel was detected.
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N
    cwe-id: CWE-200
  metadata:
    max-request: 1
  tags: panel,prometheus,pushgateway

http:
  - method: GET
    path:
      - '{{BaseURL}}'

    matchers:
      - type: word
        words:
          - '<title>Prometheus Pushgateway</title>'
# digest: 490a00463044022069b2ba27e60ef0413b16091f5cf3219139321cef1eee0d1ed0331f0ce7df2d8902200c746f137d6a422a3478b5cd09426939d196c36117d1be1a0a0e9b4e2cfb7522:922c64590222798bb761d5b6d8e72950