id: wordpress-better-wp-security

info:
  name: Solid Security – Password, Two Factor Authentication, and Brute Force Protection Detection
  author: ricardomaia
  severity: info
  reference:
    - https://wordpress.org/plugins/better-wp-security/
  metadata:
    plugin_namespace: better-wp-security
    wpscan: https://wpscan.com/plugin/better-wp-security
  tags: tech,wordpress,wp-plugin,top-100,top-200

http:
  - method: GET
    path:
      - "{{BaseURL}}/wp-content/plugins/better-wp-security/readme.txt"

    payloads:
      last_version: helpers/wordpress/plugins/better-wp-security.txt

    extractors:
      - type: regex
        part: body
        internal: true
        name: internal_detected_version
        group: 1
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'

      - type: regex
        part: body
        name: detected_version
        group: 1
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'

    matchers-condition: or
    matchers:
      - type: dsl
        name: "outdated_version"
        dsl:
          - compare_versions(internal_detected_version, concat("< ", last_version))

      - type: regex
        part: body
        regex:
          - '(?i)Stable.tag:\s?([\w.]+)'
# digest: 4b0a00483046022100d21e7a5ec7afa4bc56029f1b2edbf922b6f885d2fc409587c2317073f4132d25022100b4125205f3ede51c2dd87cff287c2e553a772c52b2e40fb9cc366005548ce1ef:922c64590222798bb761d5b6d8e72950